baseurl = "/"
title = "¿Observer or observed?"
languageCode = "en-us"
paginate = "10" # Number of posts per page
theme = "mainroad"
disqusShortname = "" # Enable comments by entering your Disqus shortname
googleAnalytics = "" # Enable Google Analytics by entering your tracking id
disableKinds = ["RSS"]

[Author]
  name = "Gaia Ciceri"
  bio = "Una breve biografia"
  avatar = "img/avatar.png"

[Params]
  subtitle = "Tutto ciò che ti circonda" # Subtitle of your site
  description = "Tutto ciò che ti circonda" # Description of your site
  opengraph = true
  twitter_cards = false
  readmore = false # Show "Read more" button in list if true
  authorbox = true
  pager = false
  post_meta = ["date", "categories"] # Order of post meta information

[Params.sidebar]
  home = "right"   # Configure layout for home page
  list = "right"   # Configure layout for list pages
  single = "right" # Configure layout for single pages
  # Enable widgets in given order
  widgets = ["search", "recent", "categories", "taglist", "social"]

[Params.widgets]
  recent_num = 5 # Set the number of articles in the "Recent articles" widget
  tags_counter = false # Enable counter for each tag in "Tags" widget (disabled by default)

[Params.widgets.social]
  facebook = "username"
  twitter = "username"
  instagram = "username"
  email = "gaia.ciceri.na@gmail.com"